drop table if exists gwas;
-- do comments work though
create table gwas(
    "DATE ADDED TO CATALOG" varchar,
    "PUBMEDID" varchar,
    "FIRST AUTHOR" varchar,
    "DATE" varchar,
    "JOURNAL" varchar,
    "LINK" varchar,
    "STUDY" varchar,
    "DISEASE/TRAIT" varchar,
    "INITIAL SAMPLE SIZE" varchar,
    "REPLICATION SAMPLE SIZE" varchar,
    "REGION" varchar,
    "CHR_ID" varchar,
    "CHR_POS" varchar,
    "REPORTED GENE(S)" varchar,
    "MAPPED_GENE" varchar,
    "UPSTREAM_GENE_ID" varchar,
    "DOWNSTREAM_GENE_ID" varchar,
    "SNP_GENE_IDS" varchar,
    "UPSTREAM_GENE_DISTANCE" varchar,
    "DOWNSTREAM_GENE_DISTANCE" varchar,
    "STRONGEST SNP-RISK ALLELE" varchar,
    "SNPS" varchar,
    "MERGED" varchar,
    "SNP_ID_CURRENT" varchar,
    "CONTEXT" varchar,
    "INTERGENIC" varchar,
    "RISK ALLELE FREQUENCY" varchar,
    "P-VALUE" varchar,
    "PVALUE_MLOG" varchar,
    "P-VALUE (TEXT)" varchar,
    "OR or BETA" varchar NULL,
    "95% CI (TEXT)" varchar,
    "PLATFORM [SNPS PASSING QC]" varchar,
    "CNV" varchar,
    "MAPPED_TRAIT" varchar,
    "MAPPED_TRAIT_URI" varchar,
    "STUDY ACCESSION" varchar,
    "GENOTYPING TECHNOLOGY" varchar
);
